-- Create Sessions Table
create table public.sessions (
  id uuid default gen_random_uuid() primary key,
  session_number integer generated by default as identity,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  duration_minutes integer,
  buy_in_amount integer not null,
  chips_per_buy_in integer not null,
  status text not null default 'active' check (status in ('active', 'completed')),
  total_pot_rs float
);

-- Create Players Table
create table public.players (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references public.sessions(id) on delete cascade not null,
  name text not null,
  buy_ins integer default 1 not null,
  chips_out float,
  net_profit float
);

-- Create Settlements Table
create table public.settlements (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references public.sessions(id) on delete cascade not null,
  from_name text not null,
  to_name text not null,
  amount float not null
);

-- Enable Row Level Security (RLS)
alter table public.sessions enable row level security;
alter table public.players enable row level security;
alter table public.settlements enable row level security;

-- Create Anonymous Access Policies (for P1, no auth yet)
create policy "Allow anonymous read all sessions" on public.sessions for select to anon using (true);
create policy "Allow anonymous insert sessions" on public.sessions for insert to anon with check (true);
create policy "Allow anonymous update sessions" on public.sessions for update to anon using (true);
create policy "Allow anonymous delete sessions" on public.sessions for delete to anon using (true);

create policy "Allow anonymous read all players" on public.players for select to anon using (true);
create policy "Allow anonymous insert players" on public.players for insert to anon with check (true);
create policy "Allow anonymous update players" on public.players for update to anon using (true);
create policy "Allow anonymous delete players" on public.players for delete to anon using (true);

create policy "Allow anonymous read all settlements" on public.settlements for select to anon using (true);
create policy "Allow anonymous insert settlements" on public.settlements for insert to anon with check (true);
create policy "Allow anonymous update settlements" on public.settlements for update to anon using (true);
create policy "Allow anonymous delete settlements" on public.settlements for delete to anon using (true);
